---

- name: wait until topic-operator is active
  shell: "{{ openshift_cli }} get deployment kafka-cluster-entity-operator -o template --template={{ json_template }} -n {{ ocp_project }}"
  vars:
    json_template: '\{\{.status.readyReplicas\}\}'
  register: result
  until: result.stdout == "1"
  retries: 60
  delay: 10
  changed_when: false

# topics
- name: create topics
  include_role:
    name: kafka_topics