---

# create project
- name: create project {{ ocp_project }}
  oc_project:
    state: present
    oc_binary: "{{ openshift_cli }}"
    name: "{{ ocp_project }}"

- name: assign user {{ project_admin }} as project admin in {{ ocp_project }}
  oc_adm_policy_user:
    state: present
    oc_binary: "{{ openshift_cli }}"
    resource_kind: role
    user: "{{ project_admin }}"
    namespace: "{{ ocp_project }}"
    rolebinding_name: "{{ project_admin }}-admin"
    resource_name: admin
  when: >
    project_admin is defined and
    project_admin is not none and
    project_admin|trim() != ""

- name: annotate project {{ ocp_project }}
  oc_project_annotate:
    state: present
    oc_binary: "{{ openshift_cli }}"
    name: "{{ ocp_project }}"
    annotations: "{{ project_annotations }}"
    debug: True
  when: >
    project_annotations is defined and
    project_annotations is not none and
    project_annotations|trim() != ""

- oc_adm_policy_user:
    state: present
    oc_binary: "{{ openshift_cli }}"
    rolebinding_name: "{{ ocp_service_account }}-{{ ocp_privileges }}"
    namespace: "{{ ocp_project }}"
    resource_kind: role
    user: "system:serviceaccount:{{ ocp_project }}:{{ ocp_service_account }}"
    resource_name: "{{ ocp_privileges }}"
  when: >
    ocp_service_account is defined and
    ocp_service_account is not none and
    ocp_service_account|trim() != "" and
    ocp_privileges is defined and
    ocp_privileges is not none and
    ocp_privileges|trim() != ""