---

jenkins_service: jenkins
jenkins_jnlp_service: jenkins-jnlp
jenkins_enable_oauth: "true"
jenkins_memory_limit: 1Gi
jenkins_cpu_limit: 1000m
jenkins_volume_capacity: 1Gi
jenkins_imagestream_namespace: openshift
jenkins_disable_administrative_monitors: "true"
jenkins_imagestream_tag: jenkins:2
jenkins_enable_fatal_error_log_file: "false"

jenkins_template: jenkins-persistent.yaml

jenkins_maven_slave_configmap_template: jenkins-maven-slave-configmap.yaml
jenkins_maven_slave_pvc_template: jenkins-maven-slave-pvc.yaml
jenkins_maven_slave_configmap: jenkins-maven-slave
jenkins_maven_slave_pvc: jenkins-maven-slave-repository

gogs_service: gogs
gogs_service_port: 3000