---

- import_role:
    name: strimzi_cluster_provisioner
    tasks_from: uninstall

- import_role:
    name: strimzi_cluster_operator
    tasks_from: uninstall

- name: delete project
  oc_project:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    name: "{{ project_kafka_cluster }}"
  when: >
    uninstall_delete_project is defined and
    uninstall_delete_project|bool == True

- name: delete project
  oc_project:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    name: "{{ ocp_project }}"
  when: >
    uninstall_delete_project is defined and
    uninstall_delete_project|bool == True