---

- name: remove {{ jenkins_service }} route
  oc_obj:
    state: absent
    oc_binary: "{{ openshift_cli }}"
    name: "{{ jenkins_service }}"
    kind: route
    namespace: "{{ ocp_project }}"

- name: remove {{ jenkins_jnlp_service }} service
  oc_obj:
    state: absent
    oc_binary: "{{ openshift_cli }}"
    name: "{{ jenkins_jnlp_service }}"
    kind: service
    namespace: "{{ ocp_project }}"

- name: remove {{ jenkins_service }} service
  oc_obj:
    state: absent
    oc_binary: "{{ openshift_cli }}"
    name: "{{ jenkins_service }}"
    kind: service
    namespace: "{{ ocp_project }}"

- name: remove {{ jenkins_service }} dc
  oc_obj:
    state: absent
    oc_binary: "{{ openshift_cli }}"
    name: "{{ jenkins_service }}"
    kind: dc
    namespace: "{{ ocp_project }}"

- name: remove {{ jenkins_maven_slave_configmap }} configmap
  oc_obj:
    state: absent
    oc_binary: "{{ openshift_cli }}"
    name: "{{ jenkins_maven_slave_configmap }}"
    kind: configmap
    namespace: "{{ ocp_project }}"

- name: remove {{ jenkins_service }} pvc
  oc_obj:
    state: absent
    oc_binary: "{{ openshift_cli }}"
    name: "{{ jenkins_service }}"
    kind: pvc
    namespace: "{{ ocp_project }}"

- name: remove {{ jenkins_maven_slave_pvc }} pvc
  oc_obj:
    state: absent
    oc_binary: "{{ openshift_cli }}"
    name: "{{ jenkins_maven_slave_pvc }}"
    kind: pvc
    namespace: "{{ ocp_project }}"

- name: remove {{ jenkins_service }}_edit rolebinding
  oc_obj:
    state: absent
    oc_binary: "{{ openshift_cli }}"
    name: "{{ jenkins_service }}_edit"
    kind: rolebinding
    namespace: "{{ ocp_project }}"

- name: remove {{ jenkins_service }} serviceaccount
  oc_obj:
    state: absent
    oc_binary: "{{ openshift_cli }}"
    name: "{{ jenkins_service }}"
    kind: sa
    namespace: "{{ ocp_project }}"