---

application_name: dispatch-service

application_configmap: dispatch-service
logging_configmap: dispatch-service-logging

postgresql_template: "{{ resources_dir }}/postgresql-persistent-template.yaml"
postgresql_service_name: dispatch-service-postgresql
postgresql_init_configmap: "{{ postgresql_service_name }}-init"
postgresql_username: jboss
postgresql_password: jboss
postgresql_database: rhpam
postgresql_max_connections: 100
postgresql_max_prepared_transactions: 100

postgresql_host: "{{ postgresql_service_name }}"

narayana_dbcp_max_total: 20

kafka_bootstrap_service: "{{ kafka_cluster }}-kafka-bootstrap.{{ project_kafka_cluster }}.svc"
kafka_bootstrap_port: 9092
kafka_bootstrap_address: "{{ kafka_bootstrap_service }}:{{ kafka_bootstrap_port }}"
kafka_groupid: dispatch-service
kafka_consumer_concurrency: 5

listener_destination_ride_event: topic-ride-event

listener_destination_driver_event: topic-driver-event

listener_destination_passenger_event: topic-passenger-event

send_destination_driver_command: topic-driver-command

send_destination_passenger_command: topic-passenger-command

dispatch_assign_driver_expire_duration: 5M

quartz_configuration: "/app/config/jbpm-quartz.properties"
quartz_datasource_dbcp_max_total: 20
quartz_clustered: true

ocp_application_template: "{{ resources_dir }}/dispatch-service-tracing-template.yaml"
ocp_binary_build_config_template: "{{ resources_dir }}/dispatch-service-binary.yaml"
ocp_pipeline_build_config_template: "{{ resources_dir }}/dispatch-service-pipeline.yaml"
ocp_application_name: dispatch-service
ocp_deployment_config: dispatch-service
ocp_binary_build_config: "{{ ocp_application_name }}-binary"
ocp_pipeline_build_config: "{{ ocp_application_name }}-pipeline"
ocp_build_imagestream: redhat-openjdk18-openshift:1.4

git_url: "gogs:3000"
git_repository: "acme/dispatch-service"

logging_style: dev

tracing_service_name: dispatch-service
tracing_reporter_log_spans: false
tracing_sampler_type: ratelimiting
tracing_sampler_param: 1
tracing_agent_host: localhost
tracing_agent_port: 6831