---

- name: Deploy driver service
  hosts: localhost
  connection: local
  gather_facts: false
  run_once: true
  vars_files:
    - group_vars/services.yml
    - group_vars/kafka_cluster.yml
    - group_vars/tools.yml

  tasks:
    - set_fact:
        playbook_name: driver-service
        ocp_project: "{{ project_services }}"
        resources_dir: "{{ ocp_dir }}/driver-service"
    - include_role:
        name: openshift_driver_service
      when: >
        ACTION is not defined or
        ACTION is none or
        ACTION|trim() == "" or
        ACTION|trim() == "create"
    - include_role:
        name: openshift_driver_service
        tasks_from: uninstall
      when: >
        ACTION is defined and
        ACTION|trim() == "uninstall"