---

- name: Deploy Prometheus
  hosts: localhost
  connection: local
  gather_facts: false
  run_once: true
  vars_files:
    - group_vars/tools.yml
    - group_vars/services.yml
    - group_vars/kafka_cluster.yml

  tasks:
    - set_fact:
        playbook_name: prometheus
        ocp_project: "{{ project_tools }}"
        resources_dir: "{{ ocp_dir }}/prometheus"
    - include_role:
        name: openshift_prometheus
      when: >
        ACTION is not defined or
        ACTION is none or
        ACTION|trim() == "" or
        ACTION|trim() == "create"
    - include_role:
        name: openshift_prometheus
        tasks_from: uninstall
      when: >
        ACTION is defined and
        ACTION|trim() == "uninstall"