---

- name: Deploy Strimzi Operator
  hosts: localhost
  connection: local
  gather_facts: false
  run_once: true
  vars_files:
    - group_vars/kafka_cluster.yml

  tasks:
    - set_fact:
        playbook_name: strimzi-operator
        ocp_project: "{{ operator_project }}-{{ cluster_provisioner }}"
        project_kafka_cluster: "{{ project_kafka_cluster }}-{{ cluster_provisioner }}"
    - include_role:
        name: openshift_strimzi_operator
      when: >
        ACTION is not defined or
        ACTION is none or
        ACTION|trim() == "" or
        ACTION|trim() == "install"
    - include_role:
        name: openshift_strimzi_operator
        tasks_from: uninstall
      when: >
        ACTION is defined and
        ACTION|trim() == "uninstall"