---

# deploy jaeger all-in-one
- name: check if jaeger deployment exists
  oc_obj:
    state: list
    oc_binary: "{{ openshift_cli }}"
    name: "{{ jaeger_service_name }}"
    namespace: "{{ ocp_project }}"
    kind: deployment
  register: deployed

- name: deploy jaeger
  shell: |
    {{ openshift_cli }} process -f {{ jaeger_template }} \
    --param=JAEGER_SERVICE_NAME={{ jaeger_service_name }} \
    | {{ openshift_cli }} create -f - -n {{ ocp_project }}
  when: deployed.results.stderr is defined and deployed.results.stderr != ""