apiVersion: kafka.strimzi.io/v1alpha1
kind: Kafka
metadata:
  name: {{ kafka_cluster }}
spec:
  kafka:
    replicas: {{ kafka_replicas }}
    listeners:
      plain: {}
      tls: {}
    config:
      offsets.topic.replication.factor: {{ kafka_offsets_topic_replication_factor }}
      transaction.state.log.replication.factor: {{ kafka_transaction_state_log_replication_factor }}
      transaction.state.log.min.isr: {{ transaction_state_log_min_isr }}
    storage:
{% if kafka_storage_type == "persistent" %}
      type: persistent-claim
      size: {{ kafka_volume_capacity }}
      deleteClaim: {{ kafka_delete_claim }}
{% endif %}
{% if kafka_storage_type == "ephemeral" %}
      type: ephemeral
{% endif %}
  zookeeper:
    replicas: {{ zookeeper_replicas }}
    storage:
{% if zookeeper_storage_type == "persistent" %}
      type: persistent-claim
      size: {{ zookeeper_volume_capacity }}
      deleteClaim: {{ zookeeper_delete_claim }}
{% endif %}
{% if zookeeper_storage_type == "ephemeral" %}
      type: ephemeral
{% endif %}    
  entityOperator:
    topicOperator:
      resources:
        request:
          cpu: "{{ topic_operator_request_cpu }}"
          memory: {{ topic_operator_request_memory }}
        limit:
          cpu: "{{ topic_operator_limit_cpu }}"
          memory: {{ topic_operator_limit_memory }}
    userOperator: {}