---

kafka_template: kafka.yaml

zookeeper_replicas: 3
# persistent, ephemeral
zookeeper_storage_type: persistent
zookeeper_volume_capacity: 1Gi
zookeeper_delete_claim: "true"

kafka_replicas: 3
# persistent, ephemeral
kafka_storage_type: persistent
kafka_volume_capacity: 2Gi
kafka_offsets_topic_replication_factor: 3
kafka_transaction_state_log_replication_factor: 3
transaction_state_log_min_isr: 2
kafka_delete_claim: "true"

topic_operator_request_cpu: 250m
topic_operator_request_memory: 250Mi
topic_operator_limit_cpu: 500m
topic_operator_limit_memory: 500Mi